# Generated by Django 5.2.8 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('presex', 'Presex'), ('marketing', 'Marketing'), ('projetista', 'Projetista'), ('gestao', 'Gestão de Pessoas')], max_length=50),
        ),
    ]
