# Generated by Django 5.2.8 on 2025-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ej_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'História',
                'db_table': 'historia',
            },
        ),
    ]
