# Generated by Django 5.2.8 on 2025-12-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_challenges_alter_project_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_id',
            new_name='project',
        ),
    ]
