# Generated by Django 5.2.8 on 2025-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
