# Generated by Django 5.2.8 on 2025-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(blank=True, max_length=150, null=True)),
                ('vision', models.CharField(blank=True, max_length=150, null=True)),
                ('values', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
